### PR TITLE
Fixed environments sometimes not selected on redeploy issue

### LINKED ISSUE #122: AMW_angular/#/deployment/: redeploy sometimes doesn't set an environment
Sometimes the environment is not set on AMW_angular/#/deployment/ when clicking the redeploy link on a single deployment.

I can reproduce it when I close chrome completely, reopen it, go to AMW_web/pages/deploy.xhtml and then click redeploy.

### PR DESCRIPTION
**Pull request by RetGal**
Fixes #122

### CODE REVIEW

File: AMW_angular/io/src/app/deployment/deployment.component.ts [hunk 1]
```diff
@@ -85,18 +85,19 @@ export class DeploymentComponent implements OnInit, AfterViewInit {
   }
 
   ngOnInit() {
+    console.log('hello `Deployment` component');
```
Comment (yvespp) [inline AMW_angular/io/src/app/deployment/deployment.component.ts]: Can you remove the log please?
